### ISSUE TITLE
train recognition only

### ISSUE THREAD

**Issue by lerndeep** [mxin262/SwinTextSpotter#1]
@mxin262  I want to train the recognition part only. could you please let me know how can I train the recognition part only by freezing the detection part to improve the recognition accuracy?

**Comment by mxin262** [comment]
@lerndeep You can freeze the other parameters except the rec_stage[https://github.com/mxin262/SwinTextSpotter/blob/da9174db260c6e71c25bc8d5e884ef2eacf57863/projects/SWINTS/swints/head.py#L58](url).

**Comment by WongVi** [comment]
@mxin262 I am new . could you please let me know the idea and lines of code I need to change for train recognition only for boosting recognition accuracy?
