### ISSUE TITLE
Change character list

### ISSUE THREAD

**Issue by khiemledev** [mxin262/SwinTextSpotter#10]
Hello everyone, I want to change character list to match my custom dataset characters. How can I do this?
I have tried to change CTLBELS, chars whenever character list appear in the code but I end up with this errror "Assertion `cur_target >= 0 && cur_target < n_classes` failed".

Thank you!

**Comment by khiemledev** [comment]
I also try to train on my custom dataset without changing the character list but still have this error:
![image](https://user-images.githubusercontent.com/28501389/162949080-91f55168-fb4f-42c5-b80d-01940175eed7.png)

**Comment by mxin262** [comment]
You can change the config like this [config](https://github.com/mxin262/SwinTextSpotter/blob/c9e81c9bba269c98b4b1121bbef40d296db9d9a9/projects/SWINTS/configs/SWINTS-swin-chn_pretrain.yaml#L11)

**Comment by khiemledev** [comment]
Thank you, I have fixed that problem ^^
