### ISSUE TITLE
关于使用本项目的一些问题

### ISSUE THREAD

**Issue by XZRRRRRR** [mxin262/SwinTextSpotter#104]
感谢您的开源分享！在我实际使用本项目时，有一些问题想和您请教：
1、在安装项目环境的detectron2时，使用您给的方式直接构建会报错（我使用的是conda虚拟环境，cuda使用的是cudatoolkit-dev，我怀疑问题可能出在这），因此我选择直接安装了detectron2依赖，这应该不会影响使用吧？
2、关于自定义数据集的训练，我按照issue以及您提供的代码构筑了自己的json文件，但我暂时没有找到使用数据集的入口，detectron2好像得自己注册数据集对吗？希望您能给我一些指导，万分感谢！！

**Comment by XZRRRRRR** [comment]
我似乎找到了入口：SwinTextSpotter/projects/SWINTS/LME/MaskLoader.py，如果我验证没有问题后，我会关闭这个issue

**Comment by XZRRRRRR** [comment]
更新一点，在安装项目环境的detectron2时，我遇到的问题是由于setup.py文件中各个依赖版本对齐问题导致的。首次出错是在omegaconf这个依赖，单独pip安装这个版本的依赖没有任何问题。另外还遇到了执行setup默认的依赖版本过高的问题，这些都可以通过看报错信息，单独pip安装解决。之后再setup就没问题了。

**Comment by mxin262** [comment]
数据入口在[这里](https://github.com/mxin262/SwinTextSpotter/blob/main/detectron2/data/datasets/builtin.py)
