### ISSUE TITLE
跑demo的时候遇到了一些问题

### ISSUE THREAD

**Issue by wu-yz** [mxin262/SwinTextSpotter#106]
我把Visualizer换成Visualizer_chn之后，想要测试一张中英文的图片，但是报了如下错误：
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\pycode\\textdetrec\\rec\\SwinTextSpotter-main\\simsun.ttc'
用Visualizer的话就是能检测一些文字出来，但是识别效果很差。
请问这怎么解决呢？
谢谢！

**Comment by mxin262** [comment]
这是中文字体文件的问题，可以把字体文件改成[这个](https://github.com/mxin262/ESTextSpotter/blob/main/simhei.ttf)试试

**Comment by wu-yz** [comment]
解决了，谢谢！
