### ISSUE TITLE
How can I make train faster？

### ISSUE THREAD

**Issue by Randy-1009** [mxin262/SwinTextSpotter#11]
Thanks to your reply and guidance, I have started training on my own dataset, but the utilization rate of the graphics card is very low. Where can I adjust to increase the memory occupation of the graphics card and speed up the training? Thank you~
![image](https://user-images.githubusercontent.com/46707940/162991927-af27f262-ad1c-42bb-950e-14915cf67b75.png)

**Comment by mxin262** [comment]
You can try to increase the batch size in [here](https://github.com/mxin262/SwinTextSpotter/blob/c9e81c9bba269c98b4b1121bbef40d296db9d9a9/projects/SWINTS/configs/Base-SWINTS_swin.yaml#L21) or increase the recognition batch size like [this](https://github.com/mxin262/SwinTextSpotter/blob/c9e81c9bba269c98b4b1121bbef40d296db9d9a9/projects/SWINTS/configs/SWINTS-swin-finetune-ctw.yaml#L10)
