### ISSUE TITLE
作者您好！为什么我用下载的模型文件去测试demo但是只detect到0instance呀TT望指教

### ISSUE THREAD

**Issue by Selvaggiar** [mxin262/SwinTextSpotter#112]
python demo/demo.py \
--config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml \
--input datasets/ocr_en_422k/GCC_train_171460144.jpg \
--output output/ocr_en \
--confidence-threshold 0.4 \
--opts MODEL.WEIGHTS work_dirs/swin_imagenet_pretrain.pth

**Comment by mxin262** [comment]
模型的权重不对，下载这个[链接](https://drive.google.com/file/d/1o6LbT0NayfIzTtJpozAqtz50wrSNnKIJ/view?usp=sharing)的权重试试

**Comment by Selvaggiar** [comment]
> 模型的权重不对，下载这个[链接](https://drive.google.com/file/d/1o6LbT0NayfIzTtJpozAqtz50wrSNnKIJ/view?usp=sharing)的权重试试

谢谢！！！
