### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by Preethse** [mxin262/SwinTextSpotter#14]
If I have to create my own dataset then where do You suggest I should do it from? Somewhere where I can get segmentation maps also for char level? May be synthtext?

**Comment by mxin262** [comment]
You can refer to this [example](https://drive.google.com/file/d/1FE17GXyGPhDk5XI3EpbXwlOv1S8txOx2/view) to convert the label into coco format. Our method does not need character-level annotation. If you want to use the character-level annotation, you can refer to [Mask TextSpotter](https://github.com/MhLiao/MaskTextSpotter) adding the character segmentation module to SwinTextSpotter. You are right. You can get the character-level for Synthtext.
