### ISSUE TITLE
About using the pretrained model to spot Vietnamese

### ISSUE THREAD

**Issue by namdo281** [mxin262/SwinTextSpotter#15]
Hello, i want to use your pretrained model which was fine tuned on vintext to spot Vietnamese. But seems like it's predicting characters in the English alphabet. I don't see where to change the alphabet in the config files, where should I take a look at to modify this?

**Comment by mxin262** [comment]
If you want to get the visualization result, you can change the Visualizer into Visualizer_vintext in[here](https://github.com/mxin262/SwinTextSpotter/blob/f29f5f3c1db84f78b3456e17d8139249f089d01e/demo/predictor.py#L52). 
If you want to evaluate, you can run the fellow code:
`python projects/SWINTS/train_net.py \
  --config-file projects/SWINTS/configs/SWINTS-swin-finetune-vintext.yaml \
  --eval-only MODEL.WEIGHTS vintext_final_model.pth`

**Comment by namdo281** [comment]
Thank you, I fixed it. Btw i find there's a bad loc [here](https://github.com/mxin262/SwinTextSpotter/blob/main/detectron2/utils/visualizer_vintext.py#L1076). I change it to 
```
        font_size = 5.0
        x, y = position

        self.output.ax.text(
            x,
            y,
            text,
            size=font_size * self.output.scale,
            family="sans-serif",
            bbox={"facecolor": "black", "alpha": 0.0, "pad": 0.0, "edgecolor": "none"},
            verticalalignment="bottom",
            horizontalalignment=horizontal_alignment,
            color=color,
            zorder=10,
            rotation=rotation,
        )
```
it works fine.

**Comment by mxin262** [comment]
Thank you for your suggestion.
