### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/totaltext/weak_voc_new.txt'

### ISSUE THREAD

**Issue by madajie9** [mxin262/SwinTextSpotter#16]
Thank you for your kindly code sharing!

And when I run :
python projects/SWINTS/train_net.py --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml --eval-only MODEL.WEIGHTS model.pth

The error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/totaltext/weak_voc_new.txt'

But I can not find this file according to dataset download.

**Comment by mxin262** [comment]
You can download it in [here](https://drive.google.com/file/d/1jNX0NQKtyMC1pnh_IV__0drgNwTnupca/view)

**Comment by madajie9** [comment]
> You can download it in [here](https://drive.google.com/file/d/1jNX0NQKtyMC1pnh_IV__0drgNwTnupca/view)

Thank you very much!
And I tested Totaltext on the model provided in git by
"
python projects/SWINTS/train_net.py --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml --eval-only MODEL.WEIGHTS tt_model_final.pth
"

There are totally 300 images and the result is as :
"
[05/07 13:32:00 d2.engine.defaults]: Evaluation results for totaltext_test in csv format:
[05/07 13:32:00 d2.evaluation.testing]: copypaste: Task: DETECTION_ONLY_RESULTS
[05/07 13:32:00 d2.evaluation.testing]: copypaste: precision,recall,hmean
[05/07 13:32:00 d2.evaluation.testing]: copypaste: 0.9134,0.8293,0.8693
[05/07 13:32:00 d2.evaluation.testing]: copypaste: Task: None-E2E_RESULTS
[05/07 13:32:00 d2.evaluation.testing]: copypaste: precision,recall,hmean
[05/07 13:32:00 d2.evaluation.testing]: copypaste: 0.7674,0.7190,0.7424
[05/07 13:32:00 d2.evaluation.testing]: copypaste: Task: Strong-E2E_RESULTS
[05/07 13:32:00 d2.evaluation.testing]: copypaste: precision,recall,hmean
[05/07 13:32:00 d2.evaluation.testing]: copypaste: 0.9042,0.7722,0.8330
"

The final result is slightly different from table 5 in the paper(I means [hmean] score)
DETECTION_ONLY_RESULTS: 88.0 -> 86.93
None-E2E_RESULTS: 74.3 -> 74.24
Strong-E2E_RESULTS: 84.1 -> 83.3

Is this slight difference acceptable?

Thanks again for your kindly reply!

**Comment by mxin262** [comment]
You can adjust the threshold for post-processing [here](https://github.com/mxin262/SwinTextSpotter/blob/fb1ddd360b128d2c7199c4b64847bb822941c181/projects/SWINTS/swints/config.py#L80). The thresholds of best detection result and e2e result are not the same. Adjust to 0.3 to get the best detection result. You can do multiple attempts and potentially get better results.

**Comment by madajie9** [comment]
> You can adjust the threshold for post-processing [here](https://github.com/mxin262/SwinTextSpotter/blob/fb1ddd360b128d2c7199c4b64847bb822941c181/projects/SWINTS/swints/config.py#L80). The thresholds of best detection result and e2e result are not the same. Adjust to 0.3 to get the best detection result. You can do multiple attempts and potentially get better results.

Thank you very much for your patient guide.
I will adjust this value and do more test.
