### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by yuha11** [mxin262/SwinTextSpotter#18]
你好，我用totaltext来预训练网络，显示内存不够，应该怎么解决？想试着把batch size改小一些但是找不到在哪里。
![test](https://user-images.githubusercontent.com/105058105/167139362-9b19f023-808e-4a61-8db7-660cfb97bf2d.jpg)

**Comment by mxin262** [comment]
You can add the key in configs to change the batch size
eg:

MODEL:
  REC_HEAD:
     BATCH_SIZE: 64
SOLVER:
   IMS_PER_BATCH: 8

**Comment by yuha11** [comment]
Thank you for your reply.

**Comment by yuha11** [comment]
can you tell us your email？We still have some questions for you
