### ISSUE TITLE
ReCTS model doesn't work

### ISSUE THREAD

**Issue by oyrq** [mxin262/SwinTextSpotter#19]
Parameter setting：
weights: rects_model_final.pth
config: ./projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml
predect data: ReCTS/icdar2019_rects_images1/*
run script: python3 demo/demo.py --opts MODEL.WEIGHTS ./weights/rects_model_final.pth

Using the above parameters does not predict results, but 'tt_model_final.pth' is right

**Comment by oyrq** [comment]
solve

**Comment by zbpjlc** [comment]
how solve is?

**Comment by zbpjlc** [comment]
how solve it?

**Comment by carolyueyueyue** [comment]
对，这个模型检测和识别没结果

**Comment by zmm288** [comment]
> solve
how to do

**Comment by Patickk** [comment]
@oyrq 
hi 请问是怎么solve的rects模型不好用的？ tt的确实可以
