### ISSUE TITLE
published model for inference demo?

### ISSUE THREAD

**Issue by Horace89** [mxin262/SwinTextSpotter#2]
I'm not sure if I understand how to use the code for inference on a single test picture, let's say `input1.jpg`. Have you published your pretrained model? If so, how do I adapt the line: 
```bash
python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml --input input1.jpg --output ./output --confidence-threshold 0.4 --opts MODEL.WEIGHTS ./output/model_final.pth
```

**Comment by mxin262** [comment]
I update the trained model link in README. You can Download it in [here](https://drive.google.com/file/d/1o6LbT0NayfIzTtJpozAqtz50wrSNnKIJ/view)

**Comment by Horace89** [comment]
Thanks!
