### ISSUE TITLE
demo_rects

### ISSUE THREAD

**Issue by JFly123456** [mxin262/SwinTextSpotter#24]
您好，我想问一下rects的demo需要如何设置啊，为什么我跑出来的效果很差呢？

**Comment by zmm288** [comment]
> 您好，我想问一下rects的demo需要如何设置啊，为什么我跑出来的效果很差呢？

你好，请问你解决了吗

**Comment by Patickk** [comment]
@JFly123456 
hi 18号就关了是有解决方法了么？
