### ISSUE TITLE
to a different value!\n{} != {}".format(key, self.name, oldval, val)

### ISSUE THREAD

**Issue by happy20200** [mxin262/SwinTextSpotter#28]
![1654562684(1)](https://user-images.githubusercontent.com/59427046/172272273-e35528ee-2d07-42ea-b0cd-8f28783293da.png)
请问这个问题是怎么回事啊

**Comment by mxin262** [comment]
Detectron2还是没装好

**Comment by happy20200** [comment]
哦哦好的吧，我再看看

在2022-06-10 ***@***.***写道：

Detectron2还是没装好
