### ISSUE TITLE
Lacking the introduction of char dictionary for recognition

### ISSUE THREAD

**Issue by TangLinJie** [mxin262/SwinTextSpotter#3]
The README doesn't show any detail about char dictionary for various datasets.
I print embedding size in rects_model_final.pth and tt_model_final.pth, getting 5000+, 107, respectively.

**Comment by mxin262** [comment]
The dictionary of tt_model_final.pth is 
` !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ˋˊ﹒ˀ˜ˇˆ˒‑` 

And the dictionary of rects_model_final.pth [in here](https://github.com/mxin262/SwinTextSpotter/blob/main/chn_cls_list.txt).

**Comment by TangLinJie** [comment]
The embedding of rec_stage is initialized by torch.eye. The length of (!"#$%&'()*+,-./0123456789:;<=>?@abcdefghijklmnopqrstuvwxyz[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ˋˊ﹒ˀ˜ˇˆ˒‑) is 103. Then I print learned embedding in tt_model_final.pth, and find that all embeddings of 107 classes are learned other than (!"#$%&'()*+,-./0123456789:;<=>?@abcdefghijklmnopqrstuvwxyz[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ˋˊ﹒ˀ˜ˇˆ˒‑).

**Comment by mxin262** [comment]
Some errors may have occurred when I typed.  The correct dictionary should look like this.
CTLABELS = [' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~','´', "~", "ˋ", "ˊ","﹒", "ˀ", "˜", "ˇ", "ˆ", "˒","‑"]

The length of CTLABELS is 106 and add a stop character.
