### ISSUE TITLE
 dataLoader

### ISSUE THREAD

**Issue by Norwalker** [mxin262/SwinTextSpotter#32]
hello,i can not find your dataLoader in train_net.py。i need construct my code to train custom dataset?

**Comment by mxin262** [comment]
Hi, If you want to train custom dataset, you can follow this [document](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) in detectron2.

**Comment by Norwalker** [comment]
thanks ，i get it .  on closer inspection, the code is primarily a text detection task i‘m bananas
