### ISSUE TITLE
dataset path

### ISSUE THREAD

**Issue by hmQ1998** [mxin262/SwinTextSpotter#33]
Hello, there are many datasets to download, how can I place them according to the dataset path?

**Comment by mxin262** [comment]
Hi, you can follow the Step 2 in readme. More imformation can be found [here](https://github.com/mxin262/SwinTextSpotter/blob/e238a4b5d0c127480a838c6245c1e5e9eb2f9d59/detectron2/data/datasets/builtin.py#L49-L63)
