### ISSUE TITLE
about rects

### ISSUE THREAD

**Issue by zmm288** [mxin262/SwinTextSpotter#34]
你好，我执行以下语句后结果并不是很好，想知道会是什么原因？
python projects/SWINTS/train_net.py   --config-file projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml 
--eval-only MODEL.WEIGHTS ./output/rects_model_final.pth

![image](https://user-images.githubusercontent.com/80579207/180598363-f0006fbf-92dd-4f50-a6de-03d09741db5c.png)

**Comment by mxin262** [comment]
Hi, since the test GT of ReCTS doesn't provide, you will need to test it [here](https://rrc.cvc.uab.es/?ch=12&com=evaluation&task=4)

**Comment by zmm288** [comment]
> Hi, since the test GT of ReCTS doesn't provide, you will need to test it [here](https://rrc.cvc.uab.es/?ch=12&com=evaluation&task=4)

非常感谢您的答复，我想知道模型是否能裁剪出检测出的文字区域，如果可以的话，我需要在哪里做修改呢？
