### ISSUE TITLE
the annotation file of CTW1500

### ISSUE THREAD

**Issue by tyxy2310** [mxin262/SwinTextSpotter#36]
if I use the ctw1500 dataset, how to get the annotation file " instances_train2017.json" and "test_ctw1500_maxlen100.json", thanks.

**Comment by tyxy2310** [comment]
> if I use the ctw1500 dataset, how to get the annotation file " instances_train2017.json" and "test_ctw1500_maxlen100.json", thanks.

I don't  see the python file to process the json file.

**Comment by tyxy2310** [comment]
Another question is the obj["rec"] key, I can't find where is the obj["rec"] from. Please reply soon, thanks a lot.

**Comment by mxin262** [comment]
You can download the annotation file [here](https://drive.google.com/file/d/1Yx3GRRUogjYYDUrprexGnPerFX3H6r_3/view). There is a problem with the original path. I update it.
"rec" means the text.

**Comment by tyxy2310** [comment]
> You can download the annotation file [here](https://drive.google.com/file/d/1Yx3GRRUogjYYDUrprexGnPerFX3H6r_3/view). There is a problem with the original path. I update it. "rec" means the text.

The train json file of totaltext dataset has some problems, which has 1538 imgs. It should have 1238 imgs in fact. Could you update the correct file or the python file processing label. Thanks a lot.

**Comment by mxin262** [comment]
Actually, there have 1255 imgs which is consistent with the official version. You can find in detectron2 log [here](https://user-images.githubusercontent.com/62656382/183273903-294f99f9-0cf5-423a-9c4c-e610079e8700.png)
