### ISSUE TITLE
text_result.json

### ISSUE THREAD

**Issue by zmm288** [mxin262/SwinTextSpotter#37]
您好，请问text_result.json中的rec是指预测出的文字吗，为什么使用中文数据集评估的时候rec中只有字母或者数字呀?需要哪里做调整吗?还有polys是预测框的点坐标吗?期待您的回复

**Comment by mxin262** [comment]
由于中文评估需要上传网站，所以这里的评估的时候，码表没有考虑中文，如果想得到中文的结果可以参考[这里]，修改一下评估的时候解码的部分(https://github.com/mxin262/SwinTextSpotter/blob/f2ebbe87810a14a28f59b91c2f6c318de461ec8d/detectron2/utils/visualizer_chn.py#L674)
