### ISSUE TITLE
 None-E2E_RESULTS

### ISSUE THREAD

**Issue by zmm288** [mxin262/SwinTextSpotter#38]
![image](https://user-images.githubusercontent.com/80579207/181277366-729f6ad9-a36e-420c-bc75-38dcd2961919.png)
你好，想请问这可能是什么原因呢

**Comment by mxin262** [comment]
什么数据集，评估中文必须要上传到网站去评估

**Comment by zmm288** [comment]
你好，是自定义的中文数据集

**Comment by mxin262** [comment]
自定义的数据集，首先先把[路径](https://github.com/mxin262/SwinTextSpotter/blob/f2ebbe87810a14a28f59b91c2f6c318de461ec8d/detectron2/evaluation/text_evaluation.py#L57)修改成你的测试集的路径，然后修改[这里]，(https://github.com/mxin262/SwinTextSpotter/blob/f2ebbe87810a14a28f59b91c2f6c318de461ec8d/detectron2/evaluation/text_evaluation.py#L435-L450)，修改方式参考[这个](https://github.com/mxin262/SwinTextSpotter/blob/f2ebbe87810a14a28f59b91c2f6c318de461ec8d/detectron2/utils/visualizer_chn.py#L674-L684)

**Comment by Huangqqqhhh** [comment]
请问一下你测试ic15的时候有问题嘛
