### ISSUE TITLE
自定义中文数据集

### ISSUE THREAD

**Issue by zmm288** [mxin262/SwinTextSpotter#39]
你好，在生成自定义的中文数据集的generator_json.py中，是否要将cV2修改成这样呢？
![image](https://user-images.githubusercontent.com/80579207/182033200-fc424ee6-ffc8-4317-8a87-2069dea12b7e.png)
这样生成的rec好像不太对，想知道是什么原因
![image](https://user-images.githubusercontent.com/80579207/182033281-70c54156-7d25-4a33-bcea-313182985c21.png)

**Comment by mxin262** [comment]
请用你自己的码表

**Comment by zmm288** [comment]
> 请用你自己的码表

感谢！
