### ISSUE TITLE
该问题与训练成本相关

### ISSUE THREAD

**Issue by zhuyue66** [mxin262/SwinTextSpotter#41]
学长(学姐)好，最近在精读您的论文并试着复现实验，请问本项目是在什么样的计算资源上（几张什么型号的卡？），训练多久完成的呢？谢谢~

**Comment by mxin262** [comment]
建议使用4张A6000，如果卡资源较少，减少batch size也是可以的。4张A6000需要大概四天多这样。

**Comment by Zhang-Chunhu** [comment]
> 
您好，是否可以使用3090（显存24G）来代替A6000进行复现工作？如果可以，需要几张3090可以成功复现（按照显存来替换的话是8张）？

**Comment by mxin262** [comment]
3090应该也是可以的，8张应该是够了
