### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by gfeng12345** [mxin262/SwinTextSpotter#46]
通过LabelME打标怎么得到JSON文件中的rec？test应该怎么制作数据集？

**Comment by mxin262** [comment]
可以参考这个[脚本](https://drive.google.com/file/d/1FE17GXyGPhDk5XI3EpbXwlOv1S8txOx2/view)，把label文件转换成coco的格式

**Comment by gfeng12345** [comment]
非常感谢您的解答，再请教一下训练时哪里用到了rec呢？我只看到evaluation 时用到了

**Comment by mxin262** [comment]
在[这里](https://github.com/mxin262/SwinTextSpotter/blob/f2ebbe87810a14a28f59b91c2f6c318de461ec8d/projects/SWINTS/swints/swints.py#L233)读入，用来训练识别器
