### ISSUE TITLE
rects_model_final.pth nothing

### ISSUE THREAD

**Issue by Patickk** [mxin262/SwinTextSpotter#47]
hi:
   python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml --input /xxx/x.jpg --output /xxxx --confidence-threshold 0.1 --opts MODEL.WEIGHTS /xxxxx/rects_model_final.pth
but i got nothing using 随机中文街景图片

when i use tt_model_final.pth for 随机英文街景图片，the result is good.
Dose it rects model upload wrong？I also see someone ask the same question, but now solve.
Please, tell me how to solve it, very thank.

**Comment by mxin262** [comment]
If you want to get the visualization result, you can change the Visualizer into Visualizer_chn [here](https://github.com/mxin262/SwinTextSpotter/blob/f29f5f3c1db84f78b3456e17d8139249f089d01e/demo/predictor.py#L52).
If you want to evaluate, you can run the fellow code:
python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml --input input1.jpg --output  ./output --confidence-threshold 0.3 --opts MODEL.WEIGHTS rects_model_final.pth

**Comment by Patickk** [comment]
@mxin262 solve, thanks!!

**Comment by CVerSMH** [comment]
> Visu

> @mxin262 solve, thanks!!



> If you want to get the visualization result, you can change the Visualizer into Visualizer_chn [here](https://github.com/mxin262/SwinTextSpotter/blob/f29f5f3c1db84f78b3456e17d8139249f089d01e/demo/predictor.py#L52). And then, you can run the fellow code: python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml --input input1.jpg --output ./output --confidence-threshold 0.3 --opts MODEL.WEIGHTS rects_model_final.pth

可以加个好友么

**Comment by CVerSMH** [comment]
> @mxin262 solve, thanks!!

您好可以加个联系方式么
