### ISSUE TITLE
LSVT training available?

### ISSUE THREAD

**Issue by jeong-tae** [mxin262/SwinTextSpotter#49]
Hi, I am trying to train LSVT dataset with this repo.

Seems, you've been trained LSVT,
https://github.com/mxin262/SwinTextSpotter/blob/e238a4b5d0c127480a838c6245c1e5e9eb2f9d59/detectron2/data/datasets/builtin.py#L58
but there is no transcription for that.

is LSVT data trainable with this code? then can you provide config files and lexicon for that?

**Comment by mxin262** [comment]
Hi, you can  follow [this](https://github.com/mxin262/SwinTextSpotter/blob/main/projects/SWINTS/configs/SWINTS-swin-chn_pretrain.yaml) to train on the LSVT.

**Comment by jeong-tae** [comment]
thanks. you mean that replacing chn to lsvt will work, right?
btw, how can I evaluate lsvt? should I submit it to icdar board?

**Comment by jeong-tae** [comment]
@mxin262 can you provide other link than [this](https://pan.baidu.com/s/1j-zlH8SfmdTtH2OnuT9B7Q)?
I don't have account for that... so I can't download it.

**Comment by mxin262** [comment]
You are right. You should submit it to icdar board to evaluate lsvt.
Due to my google drive space is limited, I only upload the [annotation](https://drive.google.com/file/d/11rM5_5OhXXN7MRBomEL_RUyv_5tIawiF/view?usp=sharing). You can download the image [here](https://drive.google.com/file/d/1E9RMFiRaRW4WdzA9Py7OimfzA82-Bwik/view)

**Comment by jeong-tae** [comment]
@mxin262 thank you. your replay is really helpful to me.
I tried with a new link, and I got an error `json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 419200878 (char 419200877)`
maybe the file is broken? checksum(md5sum) is: `3ee5fec85f0c3d03c379b7fbe6374016`
can you check that the annotation file is valid?

**Comment by mxin262** [comment]
Could you provide more details? Everything is working fine on my system. May be you can  open the file directly to see if there will be any errors. I also update the file [here](https://drive.google.com/file/d/1ufu-EciLaqpedNQJk44fUe4Te_yGCoIs/view?usp=sharing)

**Comment by jeong-tae** [comment]
@mxin262 I am sorry, it was not the problem of the LSVT json file. It was `chn_syn.json` problem.
I don't know why it occurs, but I used this [link](https://drive.google.com/u/0/uc?id=199sLThD_1e0vtDmpWrAEtUJyleS8DDTv&export=download).
md5sum for `chn_syn.json` is: `139e8cf51ad9ba205228570d88813fb4`

**Comment by mxin262** [comment]
I try to download from the google drive and use this annotation to train. It have ran 2000 iterations without finding any problems. And my environment is Ubuntu. Could you read this file normally with python?

**Comment by jeong-tae** [comment]
@mxin262 nope, I can't
```
python 3.8
>> json.load(open('chn_syn.json'))
```

returns `json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 419200878 (char 419200877)` this error.

**Comment by mxin262** [comment]
You can try running it on a different machine. And I upload another link [here](https://drive.google.com/file/d/1tC_DIRuiN8vGAD5U00z2VF4IwKtL171l/view?usp=sharing). You can try it.

**Comment by mxin262** [comment]
It works fine on my machine.
![image](https://user-images.githubusercontent.com/62656382/190865236-6dcaa8ee-0ae0-4728-b559-40a93a4061a5.png)

**Comment by jeong-tae** [comment]
md5sum chn_syn.json: `7ec90c2482c259c5727e56a4dabac955`
I can read now with your new link!

After that, I got this error
![image](https://user-images.githubusercontent.com/15841995/190881871-da926e45-be7d-4dc5-9f9b-5e3e258dd375.png)
I am using this script: `SWINTS-swin-chn_pretrain.yaml`

**Comment by mxin262** [comment]
It is  tricky. I can't reproduce the error in my device. I update the [link](https://drive.google.com/file/d/1tC_DIRuiN8vGAD5U00z2VF4IwKtL171l/view?usp=sharing).  Could you try to running it on a different machine? Or you can generate the annotation follow [this](https://drive.google.com/file/d/1FE17GXyGPhDk5XI3EpbXwlOv1S8txOx2/view) though the [official annotation](https://rrc.cvc.uab.es/?ch=16&com=downloads)

**Comment by jeong-tae** [comment]
hm.... I will figure it out soon.
@mxin262 Can you provide other labels as well? which linked to baidu.
I checked other labels which I downloaded from official site and doesn't work well: (rects, art)

**Comment by mxin262** [comment]
The annotation of ReCTS  can download [here](https://drive.google.com/drive/folders/1oXWVjC_Ar93TNf7g8O5wCg8dnSFheGfg?usp=sharing). The image of ReCTS  can download [here](https://drive.google.com/file/d/1ygDN1OHUusqzqJL2011wc2T_LX0t6Th4/view). The annotation of ArT  can download [here](https://drive.google.com/file/d/1_-Au0u4cre0R9k__yV2MDur0cl75_5nZ/view?usp=sharing). The image of ArT  can download [here](https://drive.google.com/file/d/1ss_3oYVYexSmhx7AP4cahl8Emd49Wrh8/view).

**Comment by whitebabycat** [comment]
> You are right. You should submit it to icdar board to evaluate lsvt. Due to my google drive space is limited, I only upload the [annotation](https://drive.google.com/file/d/11rM5_5OhXXN7MRBomEL_RUyv_5tIawiF/view?usp=sharing). You can download the image [here](https://drive.google.com/file/d/1E9RMFiRaRW4WdzA9Py7OimfzA82-Bwik/view)

hi!your annotataion links is broken,  can you fix it.

**Comment by jeong-tae** [comment]
@mxin262 Thank you! Everything goes well!

Btw, I tried to visualize the result with Chinese characters,
![image](https://user-images.githubusercontent.com/15841995/191441231-d2f36b1a-9e80-44ea-98eb-ff40edf08517.png)
but I can't see any Chinese characters from demo visualization.
How to change the character set to Chinese?

**Comment by mxin262** [comment]
@whitebabycat Use this [link](https://drive.google.com/file/d/1tC_DIRuiN8vGAD5U00z2VF4IwKtL171l/view). Baidu Web disk in the readme is recommended.

**Comment by mxin262** [comment]
@jeong-tae Refer to this #47
