### ISSUE TITLE
测试demo.py的时候出现了这种情况，请问作者有解决方法吗

### ISSUE THREAD

**Issue by yxyxnrh** [mxin262/SwinTextSpotter#52]
Traceback (most recent call last):
  File "demo/demo.py", line 99, in <module>
    predictions, visualized_output = demo.run_on_image(img, args.confidence_threshold, path)
  File "C:\Users\Administrator\SwinTextSpotter\demo\predictor.py", line 67, in run_on_image
    vis_output = visualizer.draw_instance_predictions(predictions=instances, path=path)
  File "c:\users\administrator\swintextspotter\detectron2\utils\visualizer.py", line 413, in draw_instance_predictions
    labels = _create_text_labels(classes, scores, self.metadata.get("thing_classes", None))
  File "c:\users\administrator\swintextspotter\detectron2\utils\visualizer.py", line 271, in _create_text_labels
    labels = [class_names[i] for i in classes]
  File "c:\users\administrator\swintextspotter\detectron2\utils\visualizer.py", line 271, in <listcomp>
    labels = [class_names[i] for i in classes]
IndexError: list index out of range

![屏幕截图 2022-09-18 093209](https://user-images.githubusercontent.com/82510221/190881825-c322b77b-3d5e-42e2-b0aa-aa642a632853.jpg)
![屏幕截图 2022-09-18 093223](https://user-images.githubusercontent.com/82510221/190881826-60d60b6e-37b5-4a55-bdfc-193151f33a27.jpg)

**Comment by mxin262** [comment]
Please provide more details.

**Comment by yxyxnrh** [comment]
作者先生，事实上是这样的，我本人是初学detectron2这个框架，想要重现一下今年cvpr上的一些项目，下载这个项目后，先按照readme提示安装后想用你提供的权重文件swin-totaltext-model先运行demo.py看下效果，测试图片是下载的total_test_image里的属于totaltext数据集的一些图片。刚开始demo时，会提示以上list index out of range错误，多python demo.py 后，虽然不报错了，但是目前检测不出图片里的instance，
输入指令：python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml --input input1.jpg --output ./output --confidence-threshold 0.4 --opts MODEL.WEIGHTS ./output/tt_model_final.pth

![image](https://user-images.githubusercontent.com/82510221/190904414-c37259f4-42e0-4e6f-bd32-ea0aad415f6f.png)
输出的output中的图片：
![image](https://user-images.githubusercontent.com/82510221/190905073-d56fbe2b-9405-4ccb-af06-460be4cdf21c.png)
![input1](https://user-images.githubusercontent.com/82510221/190905089-f84ce93c-cbf2-4665-9aa5-0a0331faf837.jpg)


以下是一些提示警告：
(yolov5) C:\Users\Administrator\SwinTextSpotter>python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml --input input1.jpg --output ./output --confidence-threshold 0.4 --opts MODEL.WEIGHTS ./output/tt_model_final.pth
[09/18 20:14:01 detectron2]: Arguments: Namespace(confidence_threshold=0.4, config_file='projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml', input=['input1.jpg'], opts=['MODEL.WEIGHTS', './output/tt_model_final.pth'], output='./output', video_input=None, w
ebcam=False)
[09/18 20:14:03 fvcore.common.checkpoint]: [Checkpointer] Loading from ./output/tt_model_final.pth ...
WARNING [09/18 20:14:04 fvcore.common.checkpoint]: Skip loading parameter 'backbone.fpn_lateral2.weight' to the model due to incompatible shapes: (256, 96, 1, 1) in the checkpoint but (256, 256, 1, 1) in the model! You might want to double check if this is expected.
WARNING [09/18 20:14:04 fvcore.common.checkpoint]: Skip loading parameter 'backbone.fpn_lateral3.weight' to the model due to incompatible shapes: (256, 192, 1, 1) in the checkpoint but (256, 512, 1, 1) in the model! You might want to double check if this is expected
.
WARNING [09/18 20:14:04 fvcore.common.checkpoint]: Skip loading parameter 'backbone.fpn_lateral4.weight' to the model due to incompatible shapes: (256, 384, 1, 1) in the checkpoint but (256, 1024, 1, 1) in the model! You might want to double check if this is expecte
d.
WARNING [09/18 20:14:04 fvcore.common.checkpoint]: Skip loading parameter 'backbone.fpn_lateral5.weight' to the model due to incompatible shapes: (256, 768, 1, 1) in the checkpoint but (256, 2048, 1, 1) in the model! You might want to double check if this is expecte
d.
WARNING [09/18 20:14:04 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
backbone.bottom_up.res2.0.conv1.norm.{bias, weight}
backbone.bottom_up.res2.0.conv1.weight
backbone.bottom_up.res2.0.conv2.norm.{bias, weight}
backbone.bottom_up.res2.0.conv2.weight
backbone.bottom_up.res2.0.conv3.norm.{bias, weight}
backbone.bottom_up.res2.0.conv3.weight
backbone.bottom_up.res2.0.shortcut.norm.{bias, weight}
backbone.bottom_up.res2.0.shortcut.weight
backbone.bottom_up.res2.1.conv1.norm.{bias, weight}
backbone.bottom_up.res2.1.conv1.weight
backbone.bottom_up.res2.1.conv2.norm.{bias, weight}
backbone.bottom_up.res2.1.conv2.weight
backbone.bottom_up.res2.1.conv3.norm.{bias, weight}
backbone.bottom_up.res2.1.conv3.weight
backbone.bottom_up.res2.2.conv1.norm.{bias, weight}
backbone.bottom_up.res2.2.conv1.weight
backbone.bottom_up.res2.2.conv2.norm.{bias, weight}
backbone.bottom_up.res2.2.conv2.weight
backbone.bottom_up.res2.2.conv3.norm.{bias, weight}
backbone.bottom_up.res2.2.conv3.weight
backbone.bottom_up.res3.0.conv1.norm.{bias, weight}

![image](https://user-images.githubusercontent.com/82510221/190904466-042df4eb-8c6d-43c1-b7d7-4de6a7b0d623.png)
![image](https://user-images.githubusercontent.com/82510221/190904579-3d71efb9-d207-4743-9c29-2bbca7bdb825.png)

WARNING [09/18 20:14:04 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  pos_embeddings.weight
  init_proposal_boxes.weight
  mask_encoding.{components, explained_variances, means}
  head.head_series.0.self_attn.{in_proj_bias, in_proj_weight}
  head.head_series.0.self_attn.out_proj.{bias, weight}
  head.head_series.0.inst_interact.dynamic_layer.{bias, weight}
  head.head_series.0.inst_interact.norm1.{bias, weight}
  head.head_series.0.inst_interact.norm2.{bias, weight}
  head.head_series.0.inst_interact.out_layer.{bias, weight}
  head.head_series.0.inst_interact.norm3.{bias, weight}
  head.head_series.0.linear1.{bias, weight}
  head.head_series.0.linear2.{bias, weight}
  head.head_series.0.norm1.{bias, weight}
  head.head_series.0.norm2.{bias, weight}
  head.head_series.0.norm3.{bias, weight}等

![image](https://user-images.githubusercontent.com/82510221/190904609-2fd12ae8-b507-4ba0-8b7f-a4aa96645e93.png)

totaltext.yaml的设置：权重文件使用的是您提供的tt_model_final_pth
![image](https://user-images.githubusercontent.com/82510221/190904537-045ce096-8d3b-4ed7-84bd-f046aff25fbf.png)

datasets数据集地址：
![image](https://user-images.githubusercontent.com/82510221/190904861-34b629e4-2e8c-46ee-a324-76498831d31b.png)

**Comment by zhoustan** [comment]
I met the same errors when trying the demo.py, and I printed the args in this function.
classes: tensor([ 2, 11])
scores: tensor([0.9862, 0.7476])
class_names: ['text']
The pic I used is attached below.
![input1](https://user-images.githubusercontent.com/42245680/229379333-a4855040-1404-4b16-a568-43a703a8fb9b.jpg)
