### ISSUE TITLE
关于rects数据集的问题

### ISSUE THREAD

**Issue by yxyxnrh** [mxin262/SwinTextSpotter#53]
你好，我想问一下，我使用rects数据集来测试demo.py的结果，发现输出的output里没有汉字，我测试totaltext上的英文数据集就有显示英文的

以下是我输入的指令：使用的model为作者您提供的rects的pth文件
python demo/demo.py --config-file projects/SWINTS/configs/SWINTS-swin-chn_finetune.yaml --input input1.jpg --output ./output --confidence-threshold 0.4 --opts MODEL.WEIGHTS ./output/rects_model_final.pth

SWINTS-swin-chn_finetune.yaml的配置：
_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
#WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "./output/rects_model_final.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
  REC_HEAD:
    POOLER_RESOLUTION: (16,40)
    RESOLUTION: (32, 80)
    BATCH_SIZE: 128
    NUM_CLASSES: 5463
DATASETS:
  TRAIN: ("rects",)
  TEST:  ("totaltext_test",)
SOLVER:
  STEPS: (140000,160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"

测试的图片：rects里的测试图
![input1](https://user-images.githubusercontent.com/82510221/191160121-1187391f-a56d-486b-ad02-8078dab77db5.jpg)

产生的检测结果：显示检测到了7个实例
![image](https://user-images.githubusercontent.com/82510221/191159883-e86580d9-06c6-45e7-bfce-4dace6b06120.png)

output结果：输出的jpg文件无汉字
![image](https://user-images.githubusercontent.com/82510221/191160182-d3bd6cf3-1cdd-4316-ab6b-8178287a1570.png)

**Comment by mxin262** [comment]
Refer to this #47

**Comment by yxyxnrh** [comment]
> Refer to this #47

thanks for your selfless help!  I have solved the problem
