### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by juneane** [mxin262/SwinTextSpotter#54]
训练的时候出现错误“RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.92 GiB total capacity; 6.76 GiB already allocated; 66.50 MiB free; 6.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"
将BANTCH_SIZE设置为1依旧显示该错误，请问作者有解决的方案吗？

**Comment by mxin262** [comment]
You can try to reduce the batch size of recognition.

**Comment by juneane** [comment]
请问作者跑这个模型需要的设备最小显存大概是多大？

**Comment by mxin262** [comment]
使用的是A6000
