### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 256, -1] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by wyc2015fq** [mxin262/SwinTextSpotter#57]
训练中文模型时出现这个问题，英文模型没问题，请问是什么原因？

**Comment by mxin262** [comment]
It may have encountered empty annotations. you can remove these annotations or use a batch size greater than 2 per gpu. I'll update the annotations later.

**Comment by Huangqqqhhh** [comment]
请问问题解决了嘛
