### ISSUE TITLE
 assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint .output/mixtrain/model_0079999.pth not found!

### ISSUE THREAD

**Issue by chlg3321** [mxin262/SwinTextSpotter#59]
assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint .output/mixtrain/model_0079999.pth not found!

**Comment by mxin262** [comment]
You can get the model_0079999.pth as follow:
`python projects/SWINTS/train_net.py \
  --num-gpus 8 \
  --config-file projects/SWINTS/configs/SWINTS-swin-mixtrain.yaml`
  
 And I also will uploadthe mixtrain model weight later.

**Comment by rayaner-zheng** [comment]
您好，是不是需要创建一个放置训练模型的文件夹，比如上面.output下的mixtrain？请问多久会保存一次模型？
