### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by CrazyBrick** [mxin262/SwinTextSpotter#60]
Hi, thanks for your sharing. But I've met some errors and wish you can give more suggestions.
```
I finished all the installation following the readme.md, then run demo.py  following getting_started.md
`
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from predictor import VisualizationDemo
  File "/XXX/SwinTextSpotter/demo/predictor.py", line 13, in <module>
    from detectron2.utils.visualizer_chn import Visualizer as Visualizer_chn
ModuleNotFoundError: No module named 'detectron2.utils.visualizer_chn'
`
```
I don't understant why “import  detectron2.utils.visualizer" is OK, but " import detectron2.utils.visualizer_chn"  as well as " import detectron2.utils.visualizer_vintext" can't be done.

**Comment by mxin262** [comment]
Could you provide more details？I guess this is because detectron2 was not installed properly.

**Comment by CrazyBrick** [comment]
> 

hi, thanks for your advice.
After reinstalling the whole env & project, it can run successfully anyway(though some errors still happened)

one suggestion: the documents belong to d2(like getting_started.md & Installation.md and readme.md in demo dir) may cause misunderstanding.
