### ISSUE TITLE
about swin_imagenet_pretrain.pth

### ISSUE THREAD

**Issue by jiangduwang** [mxin262/SwinTextSpotter#62]
hello,I would like to ask how this model was obtained.
I reported a mistake in the pre training step “AssertionError: Checkpoint swin_imagenet_pretrain.pth not found!”

**Comment by mxin262** [comment]
[Here.](https://drive.google.com/file/d/1wvzCMLJtEID8hBDu3wLpPv4xm3Es8ELC/view) You can also find this weight in README.
