### ISSUE TITLE
您好，我是一位初学者，我按照readme一步步走下来，项目跑不起来

### ISSUE THREAD

**Issue by suncy325** [mxin262/SwinTextSpotter#67]
在evaluate on Total Text, CTW1500, ICDAR2015的步骤

3. Pretrain SWINTS (e.g., with Swin-Transformer backbone)
```
python projects/SWINTS/train_net.py \
  --num-gpus 8 \
  --config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml
```

我想是我没有把下载的文件放在合适的路径，导致一直报类似的错误：
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/curve_text/syntext_word_eng/00037261.jpg'

可以请问将README中的东西全下载下来后，应该如何设置下载的文件的路径吗

**Comment by mxin262** [comment]
把下载下来的东西放到datasets目录下

**Comment by WangFeng1234567** [comment]
> 在evaluate on Total Text, CTW1500, ICDAR2015的步骤
> 
> 3. Pretrain SWINTS (e.g., with Swin-Transformer backbone)
> 
> ```
> python projects/SWINTS/train_net.py \
>   --num-gpus 8 \
>   --config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml
> ```
> 
> 我想是我没有把下载的文件放在合适的路径，导致一直报类似的错误： FileNotFoundError: [Errno 2] No such file or directory: 'datasets/curve_text/syntext_word_eng/00037261.jpg'
> 
> 可以请问将README中的东西全下载下来后，应该如何设置下载的文件的路径吗

我也是一位初学者，现在也是代码跑不起来，之前没有接触过深度学习的东西，现在复现这个代码感觉非常吃力，想请问一下相关方面的问题，感谢

**Comment by CVerSMH** [comment]
> > 在 evaluate on Total Text， CTW1500， ICDAR2015的步骤
> > 
> > 3. 预训练SWINT（例如，带有Swin-Transformer主干网）
> > 
> > ```
> > python projects/SWINTS/train_net.py \
> >   --num-gpus 8 \
> >   --config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我想是我没有把下载的文件放在合适的路径，导致一直报类似的错误： FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'datasets/curve_text/syntext_word_eng/00037261.jpg'
> > 可以请问将README中的东西全下载下来后，应该如何设置下载的文件的路径吗
> 
> 我也是一位初学者，现在也是代码跑不起来，之前没有接触过深度学习的东西，现在复现这个代码感觉非常吃力，想请问一下相关方面的问题，感谢
您好，我和您一样 本科生 需要浮现这边论文  可以加个联系方式么  一起交流

**Comment by WangFeng1234567** [comment]
不好意思，前两天太忙，没有及时回复，非常期待可以和你一起交流。我的QQ:1641549439



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 凌晨0:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mxin262/SwinTextSpotter] 您好，我是一位初学者，我按照readme一步步走下来，项目跑不起来 (Issue #67)




   
在 evaluate on Total Text， CTW1500， ICDAR2015的步骤
  
预训练SWINT（例如，带有Swin-Transformer主干网）
  python projects/SWINTS/train_net.py \   --num-gpus 8 \   --config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml  
我想是我没有把下载的文件放在合适的路径，导致一直报类似的错误： FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'datasets/curve_text/syntext_word_eng/00037261.jpg'
 可以请问将README中的东西全下载下来后，应该如何设置下载的文件的路径吗
  
我也是一位初学者，现在也是代码跑不起来，之前没有接触过深度学习的东西，现在复现这个代码感觉非常吃力，想请问一下相关方面的问题，感谢
 您好，我和您一样 本科生 需要浮现这边论文  可以加个联系方式么  一起交流

**Comment by CVerSMH** [comment]
> 把下载下来的东西放到datasets目录下

您好，我想问一下，Figure 5和公式对应不上了，是我理解错误，还是说是哪个出错了？
