### ISSUE TITLE
chn_cls_list.txt  is illegal

### ISSUE THREAD

**Issue by Hlic818** [mxin262/SwinTextSpotter#68]

**Comment by mxin262** [comment]
The chn_cls_list.txt is a binary file.

**Comment by Hlic818** [comment]
> 
我理解这个文件是中文dict吧？怎么读取这个文件呢？python用二进制方式读出来全是乱码

**Comment by Hlic818** [comment]
> The chn_cls_list.txt is a binary file.

我理解这个文件是中文dict吧？怎么读取这个文件呢？python用二进制方式读出来全是乱码

**Comment by mxin262** [comment]
You can refer to the code below. https://github.com/mxin262/SwinTextSpotter/blob/cecc1cac1a6122a671ca39c03bb4098b3675c143/detectron2/utils/visualizer_chn.py#L399-L400 https://github.com/mxin262/SwinTextSpotter/blob/cecc1cac1a6122a671ca39c03bb4098b3675c143/detectron2/utils/visualizer_chn.py#L674-L684

**Comment by Zalways** [comment]
> The chn_cls_list.txt is a binary file.

i want to make my own character_list contains Chinese and english,should i convert my .txt file into binary file like this chn_list?and how to convert this?
