### ISSUE TITLE
There is no build_swint_fpn_backbone in register, and can not use dataset aren't in detectron2. 

### ISSUE THREAD

**Issue by CTC8901228** [mxin262/SwinTextSpotter#69]
Hi,
I now stuck in these two parts. 
When I use 'python projects/SWINTS/train_net.py   --num-gpus 1   --config-file projects/SWINTS/configs/SWINTS-swin-pretrain.yaml' to run the code, the terminal shows "No object named 'build_swint_fpn_backbone' found in 'BACKBONE' registry!"

And the registry contains only 

build_resnet_backbone               │ <function build_resnet_backbone at 0x7f79802fb9d0>               │
│ build_resnet_fpn_backbone           │ <function build_resnet_fpn_backbone at 0x7f79802fbf70>           │
│ build_retinanet_resnet_fpn_backbone │ <function build_retinanet_resnet_fpn_backbone at 0x7f7980302040> │

the image and error message are shown as follows.

![Screenshot from 2023-01-14 12-46-50](https://user-images.githubusercontent.com/114205447/212453441-272f69b4-346f-4f53-a71d-7d4fe3c72ad4.png)

Also, when I change command to ''python projects/SWINTS/train_net.py   --num-gpus 1   --config-file projects/SWINTS/configs/SWINTS-R50-pretrain.yaml" since it use build_resnet_backbone

the message becomes:
![Screenshot from 2023-01-14 12-49-08](https://user-images.githubusercontent.com/114205447/212454481-27d3753e-1dd4-4679-ba40-3f9b14b1f7cb.png)

I think it is because of the problem from registry of detectron2, but I have no idea to fix it.
Thanks a lot!

BTW Chinese response is ok, but my computer can only type in Eng...

**Comment by mxin262** [comment]
The cause of the issue can be a failure to compile. You can try the environments suggested in readme. For Chinese visualization, You can refer to  #37.
