### ISSUE TITLE
使用自定义数据集报错，报错ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

### ISSUE THREAD

**Issue by 1193700079** [mxin262/SwinTextSpotter#71]
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

![image](https://user-images.githubusercontent.com/43908729/215560925-8bb767b2-f7ae-4a4d-b691-ef0ef5c6a423.png)

使用ic15  totaltext 数据集 都是能够正常训练的，想问一下作者，是我转化数据集出现了问题吗？

卡了很久了，依旧没有解决！

**Comment by 1193700079** [comment]
就是我的码表是如下：
![image](https://user-images.githubusercontent.com/43908729/215562646-7b0cd3c4-bf73-4682-bebe-98c3b564e533.png)

一共659个字符

**Comment by 1193700079** [comment]
ok 解决了  num_class 换成 660 就能够训练了

**Comment by suncy325** [comment]
> ok 解决了 num_class 换成 660 就能够训练了

老哥，求问改了num_class 也是一样咋办呀

**Comment by mxin262** [comment]
@suncy325 试试增大识别器的输出类别
