### ISSUE TITLE
请问swin_imagenet_pretrain.pth权重文件在哪里下载

### ISSUE THREAD

**Issue by hmnc** [mxin262/SwinTextSpotter#72]
按照readme 文件操作到第三步后报AssertinError: Checkpoint swin_imagenet_pretrain.pth not found!
请问预训练模型权重文件swin_imagenet_pretrain.pth和微调模型的权重文件.output/mixtrain/model_0079999.pth等这些权重文件在哪个文件夹中或者在哪里下载呢？

**Comment by kuldeeps1208** [comment]
I'm also stuck at the same point. Let me know if you get any breakthrough.

**Comment by mxin262** [comment]
You can refer to this [link](https://[drive.google.com](https://drive.google.com/file/d/1wvzCMLJtEID8hBDu3wLpPv4xm3Es8ELC/view?usp=sharing)/file/d/1wvzCMLJtEID8hBDu3wLpPv4xm3Es8ELC/view?usp=sharing)

**Comment by hmnc** [comment]
Thank you for your reply!
