### ISSUE TITLE
How can I get gt_masks for my custom dataset?

### ISSUE THREAD

**Issue by khiemledev** [mxin262/SwinTextSpotter#8]
I want to train SwinTextSpotter on my custom dataset (in totaltext format). But when I start to train, I was facing with this error:
"AttributeError: Cannot find field 'gt_masks' in the given Instances!" in line 230 of file projects/SWINTS/swints/swints.py
How can I get gt_masks for my custom dataset?

Thank you for your hard work!

**Comment by mxin262** [comment]
There is a [example scripts](https://drive.google.com/file/d/1XgI6sZAlnrNCB24Rm3OW_FULp2RhsKUs/view) to generate the data annotation.

**Comment by khiemledev** [comment]
I have already run that code and get json label but it does not have "gt_masks" inside annotations. Do you have another example?

**Comment by mxin262** [comment]
The "gt_masks" is generated by  "segmentation" in the annotations file. You can see this [function](https://github.com/mxin262/SwinTextSpotter/blob/812d5f5bd8a9ddaa2f7fb84d915a9231684fd4b3/detectron2/data/detection_utils.py#L359)

**Comment by khiemledev** [comment]
I have fixed that problem. Thanks for you quick response!
