### ISSUE TITLE
关于训练自定义数据集的问题

### ISSUE THREAD

**Issue by zhs1316** [mxin262/SwinTextSpotter#82]
您好，我想要在您提供的模型的基础上在自定义中文数据集上的进行对中文文本的训练，但是遇到了很多的问题。
1. 您提供的totaltext数据集的标注文件`totaltext_train.json`中，好像只有文本的位置，没有找到关于文本的信息，然后`weak_voc_new.txt`和`weak_voc_pair_list.txt`，这两个文件好像是一个词表，和数据集有什么关系吗？
2. 如果是自定义的数据集的话，在准备了COCO格式的标注了文本位置的文件后，文本的信息应该怎么提供呢？
3. 还有如果要进行训练的话，yaml文件要怎么修改啊，可以直接使用`SWINTS-swin-chn_pretrain.yaml`吗？

我被这几个问题困惑了很久，非常希望得到解答，不胜感激！

**Comment by zhs1316** [comment]
我明白了问题1的部分，在json中rec表示文本信息

**Comment by CVerSMH** [comment]
> 我明白了问题1的部分，在json中rec表示文本信息

您好，可以加个联系方式么，想互相学习一下

**Comment by zhs1316** [comment]
> > 我明白了问题1的部分，在json中rec表示文本信息
> 
> 您好，可以加个联系方式么，想互相学习一下

可以啊，怎么联系

**Comment by CVerSMH** [comment]
S_o_n_g______
您加我v吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mxin262/SwinTextSpotter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 晚上7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mxin262/SwinTextSpotter] 关于训练自定义数据集的问题 (Issue #82)





   
我明白了问题1的部分，在json中rec表示文本信息
  
您好，可以加个联系方式么，想互相学习一下
  
可以啊，怎么联系

**Comment by mxin262** [comment]
问题2：文本信息写到转换成码表中对应的index写到rec中。
问题3：可以用这个文件，需要修改码表类别数量 NUM_CLASSES

**Comment by CVerSMH** [comment]
> 问题2：文本信息写到转换成码表中对应的index写到rec中。 问题3：可以用这个文件，需要修改码表类别数量 NUM_CLASSES

您好，我想问一下，最后的识别器阶段，是具体用的什么，有没有推荐的类似方法，想学一下

**Comment by zhs1316** [comment]
> 问题2：文本信息写到转换成码表中对应的index写到rec中。 问题3：可以用这个文件，需要修改码表类别数量 NUM_CLASSES

好的，非常感谢您的解答，我明白了

**Comment by zhs1316** [comment]
> 问题2：文本信息写到转换成码表中对应的index写到rec中。 问题3：可以用这个文件，需要修改码表类别数量 NUM_CLASSES

**Comment by xiaoboluo6** [comment]
> 我明白了问题1的部分，在json中rec表示文本信息

我也可以向您请教一下  自制数据集不会训练

**Comment by XIAOXIAOXIAO222111** [comment]
> > > 我明白了问题1的部分，在json中rec表示文本信息
> > 
> > 
> > 您好，可以加个联系方式么，想互相学习一下
> 
> 可以啊，怎么联系

您好，可以加一下联系方式么，想学习一下
