### ISSUE TITLE
AttributeError: 'TextEvaluator' object has no attribute '_text_eval_gt_path'

### ISSUE THREAD

**Issue by Kelsey-Zhao** [mxin262/SwinTextSpotter#9]
The result shows 
`AttributeError: 'TextEvaluator' object has no attribute '_text_eval_gt_path'`
when I test on the ReCTS test set. Then is there any files to download to solve this problem?

**Comment by mxin262** [comment]
ReCTS does not provide annotations for the test set, you may need to submit the results in the [official website](https://rrc.cvc.uab.es/?ch=12).

**Comment by Huangqqqhhh** [comment]
为什么测试IC15也出现这样的错误
